package de.leo.android.testfeature;

import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.NotificationCompat;
import android.support.v4.app.NotificationManagerCompat;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;

public class MainActivity extends AppCompatActivity {
    private final static int ID_NOTIFICATION_TEST = 1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button b;
        b = (Button)findViewById(R.id.btnNotifyMaterialShareIcon);
        assert b != null;
        b.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                createNotification(v.getContext(), "Predefined Material Icon (Share)", R.drawable.ic_share_black_24dp);
            }
        });

        b = (Button)findViewById(R.id.btnNotifyMaterialCheckboxIcon);
        assert b != null;
        b.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                createNotification(v.getContext(), "Predefined Material Icon (Checkbox)", R.drawable.ic_check_box_black_24dp);
            }
        });

        b = (Button)findViewById(R.id.btnNotifyLeo);
        assert b != null;
        b.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                createNotification(v.getContext(), "Generated by Inkskape", R.drawable.ic_app_notify);
            }
        });

    }

    private void createNotification(Context context, String msg, int iconId) {
        NotificationCompat.Builder nb = new NotificationCompat.Builder(context)
                .setContentText(msg)
                .setContentTitle("Notification Title")
                .setSmallIcon(iconId)
                .setContentIntent(PendingIntent.getActivity(context, 0, new Intent(context, MainActivity.class), PendingIntent.FLAG_UPDATE_CURRENT));

        NotificationManagerCompat nm = NotificationManagerCompat.from(context);
        nm.notify(ID_NOTIFICATION_TEST, nb.build());
    }
}
